[package]
name = "omni-utils"
edition.workspace = true
version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
near-sdk.workspace = true

omni-utils-derive.workspace = true
